### ISSUE TITLE
Visual Studio 2017 crashes on replace spelling

### ISSUE THREAD

**Issue by vladoriginal** [EWSoftware/VSSpellChecker#182] opened 2018-09-26 11:58 UTC
I have Microsoft Visual Studio Professional 2017 
Version 15.8.4
VisualStudio.15.Release/15.8.4+28010.2026

Got Visual Studio crashed several times on replacing words in comments by Alt+Enter then Enter.
![image](https://user-images.githubusercontent.com/11050189/46078267-53376b80-c19c-11e8-8698-401d0529f2ae.png)

What diagnostics could I provide?

**Comment by EWSoftware** [comment] 2018-09-26 18:44
You can try starting Visual Studio with [logging enabled](https://docs.microsoft.com/en-us/visualstudio/ide/reference/log-devenv-exe?view=vs-2015).  That should give something to go on.

**Comment by lnagl** [comment] 2018-09-27 12:29
I am encountering the same issue, both with Alt-Enter+Enter and with the mouse.  I have a log, but I would rather not post it on a public forum.  I don't think there's anything interesting in it; it remains unchanged from before and after I attempt to correct a word.

**Comment by EWSoftware** [comment] 2018-09-27 14:49
@lnagl If you don't want to post it publically, you can e-mail it to me.  If you're not running the latest release of Visual Studio 2017, try updating it as that may resolve it.  It has been reported before but I've never been able to reproduce the problem.  Additional info was recently provided (#151) and it should be fixed for the next release.

**Comment by lnagl** [comment] 2018-09-27 14:56
Unfortunately I can't change the version of my installation (15.2/26430.6) due to my work requiring all tool versions to be the same for all developers.  I'll wait for your next version and see if the issue persists.

**Comment by EWSoftware** [comment] 2018-09-27 19:55
The next release will require a minimum of 15.5 since I'd already made code changes against a newer releases of the SDK assemblies and I didn't want to go back further and undo those changes as they'd require going back to some obsolete API methods.

You can try going back to the [2017.12.29.0](https://github.com/EWSoftware/VSSpellChecker/releases/tag/v2017.12.29.0) release.  That should work if it's an issue with the SDK reference assemblies.  You'd just have to go into the Extensions and Updates option in Visual Studio and uncheck the option to keep the extension up to date automatically.

**Comment by vladoriginal** [comment] 2018-10-02 19:34
Seems no crashes on **15.8.5**
Microsoft Visual Studio Professional 2017 
Version 15.8.5
VisualStudio.15.Release/15.8.5+28010.2036

**Comment by vladoriginal** [comment] 2018-10-03 18:49
No, still got a crash.

### From Windows event log:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.FrameworkElement.ChangeLogicalParent(System.Windows.DependencyObject)
   at System.Windows.FrameworkElement.AddLogicalChild(System.Object)
   at System.Windows.Controls.Decorator.set_Child(System.Windows.UIElement)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb+<ShowPreviewAsync>d__60.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb+<OnMenuItemGotKeyboardFocus>d__59.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

```
Faulting application name: devenv.exe, version: 15.8.28010.2036, time stamp: 0x5ba2ae3b
Faulting module name: KERNELBASE.dll, version: 10.0.17134.165, time stamp: 0xfa43f4b2
Exception code: 0xe0434352
Fault offset: 0x0010ddc2
Faulting process id: 0x7040
Faulting application start time: 0x01d4566754020913
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 374d6d35-9647-4dec-82cb-78e1bc4a4cbe
Faulting package full name: 
Faulting package-relative application ID: 
```

### VS Log ending:
```xml
 <entry>
    <record>6675</record>
    <time>2018/10/03 18:32:15.635</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering TryPromoteItem</description>
  </entry>
  <entry>
    <record>6676</record>
    <time>2018/10/03 18:32:15.636</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering PromoteItemAt and found the index of the item to be 8</description>
  </entry>
  <entry>
    <record>6677</record>
    <time>2018/10/03 18:32:15.828</time>
    <type>Information</type>
    <source>Manage Visual Studio Performance</source>
    <description>End execution cost summary for IdeModeChange scenario and ToolWindow component</description>
  </entry>
  <entry>
    <record>6678</record>
    <time>2018/10/03 18:32:15.829</time>
    <type>Information</type>
    <source>Manage Visual Studio Performance</source>
    <description>End execution cost summary for IdeModeChange scenario and ToolWindow component</description>
  </entry>
  <entry>
    <record>6679</record>
    <time>2018/10/03 18:32:22.015</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering AddItem. Persistence data for item: C:\***\***\ActivityWorkerCore\Services\AuthClient.cs|00000000-0000-0000-0000-000000000000|0,0</description>
  </entry>
  <entry>
    <record>6680</record>
    <time>2018/10/03 18:32:22.015</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering TryPromoteItem</description>
  </entry>
  <entry>
    <record>6681</record>
    <time>2018/10/03 18:32:22.015</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering PromoteItemAt and found the index of the item to be 8</description>
  </entry>
  <entry>
    <record>6682</record>
    <time>2018/10/03 18:32:24.846</time>
    <type>Information</type>
    <source>Manage Visual Studio Performance</source>
    <description>End execution cost summary for IdeModeChange scenario and ToolWindow component</description>
  </entry>
  <entry>
    <record>6683</record>
    <time>2018/10/03 18:32:24.846</time>
    <type>Information</type>
    <source>Manage Visual Studio Performance</source>
    <description>End execution cost summary for IdeModeChange scenario and ToolWindow component</description>
  </entry>
  <entry>
    <record>6684</record>
    <time>2018/10/03 18:32:25.236</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering AddItem. Persistence data for item: C:\***\***\TPBugReporting\TPRestXml.cs|00000000-0000-0000-0000-000000000000|0,0</description>
  </entry>
  <entry>
    <record>6685</record>
    <time>2018/10/03 18:32:25.236</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering TryPromoteItem</description>
  </entry>
  <entry>
    <record>6686</record>
    <time>2018/10/03 18:32:25.236</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering PromoteItemAt and found the index of the item to be 8</description>
  </entry>
  <entry>
    <record>6687</record>
    <time>2018/10/03 18:32:25.365</time>
    <type>Information</type>
    <source>Manage Visual Studio Performance</source>
    <description>End execution cost summary for IdeModeChange scenario and ToolWindow component</description>
  </entry>
  <entry>
    <record>6688</record>
    <time>2018/10/03 18:32:25.365</time>
    <type>Information</type>
    <source>Manage Visual Studio Performance</source>
    <description>End execution cost summary for IdeModeChange scenario and ToolWindow component</description>
  </entry>
  <entry>
    <record>6689</record>
    <time>2018/10/03 18:32:52.230</time>
    <type>Information</type>
    <source>Manage Visual Studio Performance</source>
    <description>End execution cost summary for IdeModeChange scenario and ToolWindow component</description>
  </entry>
  <entry>
    <record>6690</record>
    <time>2018/10/03 18:32:52.230</time>
    <type>Information</type>
    <source>Manage Visual Studio Performance</source>
    <description>End execution cost summary for IdeModeChange scenario and ToolWindow component</description>
  </entry>
  <entry>
    <record>6691</record>
    <time>2018/10/03 18:36:44.092</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering OnAddVerbInvoked</description>
  </entry>
  <entry>
    <record>6692</record>
    <time>2018/10/03 18:36:44.092</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering AddItem. Persistence data for item: C:\***\***\TPBugReporting\TPRestXml.cs</description>
  </entry>
  <entry>
    <record>6693</record>
    <time>2018/10/03 18:36:44.092</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering TryPromoteItem</description>
  </entry>
  <entry>
    <record>6694</record>
    <time>2018/10/03 18:36:44.092</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering PromoteItemAt and found the index of the item to be 5</description>
  </entry>
  <entry>
    <record>6695</record>
    <time>2018/10/03 18:36:48.710</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering OnAddVerbInvoked</description>
  </entry>
  <entry>
    <record>6696</record>
    <time>2018/10/03 18:36:48.710</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering AddItem. Persistence data for item: C:\***\***\TPBugReporting\TPRestXml.cs</description>
  </entry>
  <entry>
    <record>6697</record>
    <time>2018/10/03 18:36:48.710</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering TryPromoteItem</description>
  </entry>
  <entry>
    <record>6698</record>
    <time>2018/10/03 18:36:48.710</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering PromoteItemAt and found the index of the item to be 0</description>
  </entry>
  <entry>
    <record>6699</record>
    <time>2018/10/03 18:36:56.858</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering OnAddVerbInvoked</description>
  </entry>
  <entry>
    <record>6700</record>
    <time>2018/10/03 18:36:56.858</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering AddItem. Persistence data for item: C:\***\***\TPBugReporting\TPRestXml.cs</description>
  </entry>
  <entry>
    <record>6701</record>
    <time>2018/10/03 18:36:56.858</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering TryPromoteItem</description>
  </entry>
  <entry>
    <record>6702</record>
    <time>2018/10/03 18:36:56.858</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering PromoteItemAt and found the index of the item to be 0</description>
  </entry>
  <entry>
    <record>6703</record>
    <time>2018/10/03 18:36:57.605</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering AddItem. Persistence data for item: C:\***\***\TPBugReporting\BugReporting.cs|00000000-0000-0000-0000-000000000000|0,0</description>
  </entry>
  <entry>
    <record>6704</record>
    <time>2018/10/03 18:36:57.605</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering TryPromoteItem</description>
  </entry>
  <entry>
    <record>6705</record>
    <time>2018/10/03 18:36:57.605</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering PromoteItemAt and found the index of the item to be 5</description>
  </entry>
  <entry>
    <record>6706</record>
    <time>2018/10/03 18:37:00.152</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering OnAddVerbInvoked</description>
  </entry>
  <entry>
    <record>6707</record>
    <time>2018/10/03 18:37:00.152</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering AddItem. Persistence data for item: C:\***\***\TPBugReporting\BugReporting.cs</description>
  </entry>
  <entry>
    <record>6708</record>
    <time>2018/10/03 18:37:00.152</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering TryPromoteItem</description>
  </entry>
  <entry>
    <record>6709</record>
    <time>2018/10/03 18:37:00.152</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Did not find item to promote</description>
  </entry>
  <entry>
    <record>6710</record>
    <time>2018/10/03 18:37:00.153</time>
    <type>Information</type>
    <source>CodeContainerTracing</source>
    <description>Entering MruItemsStoreServiceDecorator.AddMRUItem. Item category: 01235aad-8f1b-429f-9d02-61a0101ea275, lpszItem: C:\***\***\TPBugReporting\BugReporting.cs|{00000000-0000-0000-0000-000000000000}||False</description>
  </entry>
  <entry>
    <record>6711</record>
    <time>2018/10/03 18:37:03.400</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering OnAddVerbInvoked</description>
  </entry>
  <entry>
    <record>6712</record>
    <time>2018/10/03 18:37:03.400</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering AddItem. Persistence data for item: C:\***\***\TPBugReporting\BugReporting.cs</description>
  </entry>
  <entry>
    <record>6713</record>
    <time>2018/10/03 18:37:03.400</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering TryPromoteItem</description>
  </entry>
  <entry>
    <record>6714</record>
    <time>2018/10/03 18:37:03.400</time>
    <type>Information</type>
    <source>MruList</source>
    <description>Entering PromoteItemAt and found the index of the item to be 0</description>
  </entry>
</activity>
```

**Comment by EWSoftware** [comment] 2018-10-03 19:53
The logs don't reference the spell checker or any of its assemblies so unfortunately they don't help.  More likely than not, it's caused by differences in an SDK assembly or dependency.  As noted, the next release may help resolve that.  As such, I'm going to close this for now.

**Closed by EWSoftware** 2018-10-03 19:53 UTC
