### ISSUE TITLE
False positives in Find window and Git Commit message textbox

### ISSUE THREAD

**Issue by AntonyCorbett** [EWSoftware/VSSpellChecker#272] opened 2023-02-21 17:45 UTC
The extension is showing false positives when typing text into the Find window and Git commit text boxes in VS 2022 v17.4.5

![image](https://user-images.githubusercontent.com/24551146/220420520-3dcbea2d-bac6-4f16-bbe5-6da9ce53f906.png)

**Comment by EWSoftware** [comment] 2023-02-21 21:00
Duplicate of #189.  The workaround is to restart Visual Studio.

**Comment by AntonyCorbett** [comment] 2023-02-21 21:17
@EWSoftware thanks - I did search the Issues 😀

**Comment by AntonyCorbett** [comment] 2023-02-22 11:11
@EWSoftware Restarting VS doesn't fix the issue. I'll investigate further.

**Comment by AntonyCorbett** [comment] 2023-02-22 11:56
@EWSoftware I have turned off the **Visual Studio WPF Text Boxes** option in the Global Spell Checker Configuration Settings (see below) but the spell checker is still active in Visual Studio's WPF textboxes (I have restarted VS to be sure). Do I understand correctly that if I uncheck this checkbox it should prevent the spell checker from using `WpfTextBoxSpellChecker`?

![image](https://user-images.githubusercontent.com/24551146/220613133-f374fb9d-8816-4905-a67e-95ae25a8ce3f.png)

**Comment by AntonyCorbett** [comment] 2023-02-22 13:49
@EWSoftware Disabling Resharper (and restarting VS) fixes the issue associated with false positives in WPF textboxes. However, I am still unable to prevent spell checking in WPF textboxes altogether using the Global Spell Checker Configuration Settings, `EnableWpfTextBoxSpellChecking` option.

**Comment by AntonyCorbett** [comment] 2023-02-22 14:57
> @EWSoftware I have turned off the **Visual Studio WPF Text Boxes** option in the Global Spell Checker Configuration Settings (see below) but the spell checker is still active in Visual Studio's WPF textboxes (I have restarted VS to be sure). Do I understand correctly that if I uncheck this checkbox it should prevent the spell checker from using `WpfTextBoxSpellChecker`?

See #273

**Comment by EWSoftware** [comment] 2023-02-22 16:23
Thanks for the fix and the info on Resharper.  I don't use that so it's probably why I've never been able to duplicate the issue.

**Closed** 2023-02-22 16:32 UTC
