### ISSUE TITLE
Spell check solution or project throws "Could not load file or assembly" exception.

### ISSUE THREAD

**Issue by RomanVakhterov** [EWSoftware/VSSpellChecker#184] opened 2018-10-01 14:29 UTC
When trying to run "Spell Check Solution/Project" throws exception "Could not load file or assembly Microsoft.VisualStudio.Threading"

![image](https://user-images.githubusercontent.com/28161835/46294749-57bca500-c54b-11e8-9baf-ee31019973e3.png)

**Comment by EWSoftware** [comment] 2018-10-01 16:19
Duplicate of #156 and #174.  Update to the latest release of Visual Studio and it should fix it.

**Closed by EWSoftware** 2018-10-01 16:19 UTC
Labels: Duplicate
