### ISSUE TITLE
Latest update breaks ignore words files/support

### ISSUE THREAD

**Issue by smaillet-ms** [EWSoftware/VSSpellChecker#285] opened 2023-05-15 19:30 UTC
After updating to the latest version of this add-in, the existing "ignored words" dictionary is being ignored. Worse is that I can't even add new words in context via the R-Click context menu. The menu has an option to add words to the ignored list, but that now has an arrow icon on the far right, indicating a "sub menu" but click on the menu item or the submenu arrow icon does nothing and the word remains un-ignored.

**Comment by EWSoftware** [comment] 2023-05-15 20:12
Duplicate of #284.  I've just published an update that fixes it and it should be available shortly.

**Closed** 2023-05-22 15:29 UTC
