### ISSUE TITLE
checker spellchecks interpolated strings 

### ISSUE THREAD

**Issue by bentheiii** [EWSoftware/VSSpellChecker#36] opened 2015-07-09 23:22 UTC
in c#6 there's the feature to interpolate string (eg: $"{2*6}" would come out as "12") but the extension treats the code inside the brackets as something that needs spellchecking.

**Comment by EWSoftware** [comment] 2015-07-10 02:00
Duplicate of #22.  Already fixed but not yet published.  I'll probably publish an update once VS2015 is out and I've installed it.

**Closed by EWSoftware** 2015-07-10 02:00 UTC
Labels: Duplicate
