### ISSUE TITLE
Allow VSSpellChecker to check code

### ISSUE THREAD

**Issue by dalibor983** [EWSoftware/VSSpellChecker#192] opened 2019-03-23 12:18 UTC
Can be allowed SpellChecker to check code, not only comments. For example variable names, method names, class names, etc.

I think that older versions of Visual Studio have the ability to check spell mistakes in the code but Visual Studio 2017 does not.

I do not want to install ReSharper only because it has a spell checker extension.

**Comment by EWSoftware** [comment] 2019-03-23 19:50
Duplicate of #111.  I don't have a timeline for implementation though.

**Closed** 2019-03-30 22:49 UTC
Labels: Duplicate

**Comment by TanvirArjel** [comment] 2020-03-23 04:16
@EWSoftware Without spell checking for variable names, method names, class names, etc. I found it no useful. This is should have been the first priority of spell checking.
