### ISSUE TITLE
Crash when adding a blob

### ISSUE THREAD

**Issue by robertson-bauercontrols** [EWSoftware/VSSpellChecker#300] opened 2023-08-10 15:51 UTC
When I'm editing the file, and want to add a new section for .txt files, I'm getting a VS crash

![image](https://github.com/EWSoftware/VSSpellChecker/assets/55808281/3b6ed3bf-763a-45ae-bee6-54d1d9c48b52)

![image](https://github.com/EWSoftware/VSSpellChecker/assets/55808281/eca56551-a2a7-4e08-a2c8-454ee1408a1b)

v2023.5.15.1

**Comment by EWSoftware** [comment] 2023-08-11 14:10
Duplicate of #293.  It is fixed and I'll publish an update soon.

**Closed by EWSoftware** 2023-08-11 14:10 UTC
