### ISSUE TITLE
AD0001 on the latest VS 2022

### ISSUE THREAD

**Issue by vmelamed** [EWSoftware/VSSpellChecker#317] opened 2024-12-04 21:43 UTC
I have the latest Visual Studio:
> Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
> Version 17.12.3

And installed a fresh plug-in. Now, the spell-checker works fine, but all my projects fail with **AD0001**:

>Analyzer 'VisualStudio.SpellChecker.CodeAnalyzer.CSharpSpellCheckCodeAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'VisualStudio.SpellChecker.Common, Version=2021.7.27.0, Culture=neutral, PublicKeyToken=c626d3cbee5c69d2'. The system cannot find the file specified.'.
Exception occurred with following context:
Compilation: Delinea.ResourceName.Common
SyntaxTree: C:\repos\Delinea\Delinea.ResourceName\src\Delinea.ResourceName.Common\DrnConverterSystemTextJson.cs
>
> System.IO.FileNotFoundException: Could not load file or assembly 'VisualStudio.SpellChecker.Common, Version=2021.7.27.0, Culture=neutral, PublicKeyToken=c626d3cbee5c69d2'. The system cannot find the file specified.
File name: 'VisualStudio.SpellChecker.Common, Version=2021.7.27.0, Culture=neutral, PublicKeyToken=c626d3cbee5c69d2'
   at VisualStudio.SpellChecker.CodeAnalyzer.CSharpSpellCheckCodeAnalyzer.AnalyzeSyntaxTree(SyntaxTreeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
>
>
> Suppress the following diagnostics to disable this analyzer: VSSpell001, VSSpell002

Am I missing something?

**Comment by EWSoftware** [comment] 2024-12-05 00:13
Duplicate of #316

**Closed** 2024-12-06 14:58 UTC
