### ISSUE TITLE
Can you add spell checking for identifiers ?

### ISSUE THREAD

**Issue by arthurvaverko** [EWSoftware/VSSpellChecker#138] opened 2017-09-23 03:49 UTC

**Comment by EWSoftware** [comment] 2017-09-23 22:48
Assuming you mean spell check them in code, this would be a duplicate of #111

**Comment by arthurvaverko** [comment] 2017-09-24 07:08
ho .. got it .. the title did not really told me as much.. but i read the
content now and you're right its a duplicate...

**Closed** 2017-09-24 18:55 UTC
