### ISSUE TITLE
Support Variable name using either camel casing or underscores

### ISSUE THREAD

**Issue by oren-cybereason** [EWSoftware/VSSpellChecker#162] opened 2018-07-02 10:49 UTC
Hi,
I would like to implement so it also spell checks variable names in the following systems: 
- polish notation
- underscores between word
- CamelCasing

**Comment by EWSoftware** [comment] 2018-07-02 14:31
Assuming you mean in comments, see the [General Settings](http://ewsoftware.github.io/VSSpellChecker/html/b4a8726f-5bee-48a4-81a9-00b1be332607.htm) category options "Ignore words in mixed case" (set it to No and it will split mixed case words and spell check them separately) and "Treat underscores as separators" (set it to Yes and it will split words on the underscore and spell check them separately).

Regarding polish notation, as long as they're followed by an uppercase letter with "Ignore words in mixed case" set to No, they'll be treated as words.  You'll need to add them to the Ignored Words list so that they aren't flagged as misspellings.

If you are referring to variables in actual code, that isn't supported yet but may be in the future (#111).

**Comment by oren-cybereason** [comment] 2018-07-03 15:46
That was what I meant I have a hackathon at work and was offering to implement this feature. In the wiki it says to open an issue for it so that's what I did. At the time I wrote the feature I am suggesting but it was for Visual studio 2005 and in visual basic in a company I worked in.

**Comment by EWSoftware** [comment] 2018-08-18 22:54
Since there's been no further comment on this and it is basically a duplicate of #111, I'm going to close this issue.  Post any further comments in issue #111.  Thanks.

**Closed by EWSoftware** 2018-08-18 22:54 UTC
